### ISSUE TITLE
LLM singleton methods

### ISSUE THREAD

**Issue by 0x1eef** [antaz/llm#2]
I think it would be nice to have an API that hide the details of LLM::~ChatGPT~OpenAI.new(...):
```
LLM.openai(secret).complete "Hello?"
LLM.gemini(secret).complete "Hello?"
```

What do you think?

**Comment by antaz** [comment]
Do you think we should only expose the singletons? or keep the classic API exposed as well?

**Comment by 0x1eef** [comment]
> Do you think we should only expose the singletons? or keep the classic API exposed as well?
We could have both. Going further, I was thinking that the singleton methods could be used to lazy-load a given provider. For example:

```ruby
def openai(secret)
  require_relative "providers/openai" unless defined?(LLM::OpenAI)
  LLM::OpenAI.new(secret)
end
```

And by default, no providers are loaded with `require "llm"`. What do you think ?

**Comment by antaz** [comment]
Sounds good to me.
