### ISSUE TITLE
[OpenAI] 'host' should not be hardcoded

### ISSUE THREAD

**Issue by 0x1eef** [antaz/llm#39]
For example, I came across a self-hosted solution that claims to have a ChatGPT-compatible API:
https://github.com/exo-explore/exo

A sample is here: 
https://github.com/exo-explore/exo/blob/main/exo/api/chatgpt_api.py

It appears to at least implement the Completion API, and more that we don't.
So it could be useful to be able to plug in your own LAN host to `LLM.openai` ?
What do you think ?

**Comment by antaz** [comment]
Many applications connect to OpenAI compatible APIs by proxing `api.openai.com`.
Our approach of hardcoding the HOST is correct, but i can see the merit of allowing `host` to be passed to the `OpenAI` constructor. It means that we are supporting OpenAI compatible APIs through the same interface.

**Comment by 0x1eef** [comment]
Fixed by #45
