### ISSUE TITLE
'thread' is ambigious 

### ISSUE THREAD

**Issue by 0x1eef** [antaz/llm#50]
Especially in the context of programming, `thread` could be easily misunderstood as something else (like a separate thread of execution / `Thread.new`). I suggest we _at least_ support an alias:

```ruby
bot = llm.openai(key)
bot.chat "hello"
bot.messages.each do |message|
  # ..
end
```

**Comment by antaz** [comment]
I have always been skeptical about that too. Ready to change it if we have a better idea
